### ISSUE TITLE
sketch.js not working properly 

### ISSUE THREAD

**Issue by imjp19** [yashovardhan/developer-portfolio#1]
sketch.js not working properly in the header section because of pointer-events property is auto in `.page-wrapper header .logo` change to none. It works perfectly.
change
`pointer-events: auto;`
to
`pointer-events: none;`

and the personal website is awesome. And can I use this for my website?

Thank you

**Comment by yashovardhan** [comment]
Hey, @imjp19 Thanks for pointing this out! You can feel free to use this project as your website. 

Also, would you like to send over a PR for fixing this issue?

**Comment by imjp19** [comment]
I can't, because in your repo CSS file not available. Can you please check once. because I found the issue from inspect menu.

**Comment by imjp19** [comment]
@yashovardhan now the issue is fixed :) 

Thank you

**Comment by yashovardhan** [comment]
I just noticed the CSS file not being present here as well. Redefined the `gitignore` which was causing this issue. The CSS file can now be found at https://github.com/yashovardhan/developer-portfolio/blob/main/assets/css/style.css

The error is fixed in the demo which is hosted from a private repository. The error still is present in this repo. Can you send a PR to fix it?

**Comment by imjp19** [comment]
I think the issue was fixed and I checked both the CSS file as well as your live site with inspect menu.
Thank you for looking into it :)
